# Site settings
title: Mr.Galen's Blog
header-img: img/home-bg.jpg
email: 275497985@qq.com
description: "Galen的Blog"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  Galen-Yip
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
